/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaEscritorio;

import controlador.ControladorAprobarRecargas;
import controlador.VistaAprobarRecarga;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Administrador;
import logica.BonificacionAsignada;
import logica.Fachada;
import logica.PeajeException;
import logica.Recarga;

/**
 *

 */
public class AprobacionRecargasDialogo extends javax.swing.JDialog implements VistaAprobarRecarga{

    /**
     * Creates new form AprobacionRecargas
     */
    private ControladorAprobarRecargas controlador;
    ArrayList<Recarga> recargas = new ArrayList();
    
    public AprobacionRecargasDialogo(java.awt.Frame parent, boolean modal, Administrador admin) {
        super(parent, modal);
        initComponents();
        this.controlador = new ControladorAprobarRecargas(admin, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPendientes = new javax.swing.JTable();
        btnAprobar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aprobación de recargas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Recargas pendientes:");

        tPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Propietario", "Monto"
            }
        ));
        jScrollPane1.setViewportView(tPendientes);

        btnAprobar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAprobar.setText("Aprobar");
        btnAprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprobarActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAprobar)
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAprobar))
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobarActionPerformed
        int index = tPendientes.getSelectedRow();
        Recarga seleccionado = null;
        if(index>-1){
            seleccionado = this.recargas.get(index); 
        }
        try {
            controlador.aprobar(seleccionado);
        } catch (PeajeException ex) {
            error(ex.getMessage());
        }

    }//GEN-LAST:event_btnAprobarActionPerformed

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
      this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprobar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tPendientes;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarCargas(ArrayList<Recarga> recargas) {
        this.recargas=recargas;
        
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Fecha");
        datos.addColumn("Propietario");
        datos.addColumn("Monto");

        datos.setRowCount(recargas.size());
        int fila = 0;
        for(Recarga r:recargas){
            Format f = new SimpleDateFormat("dd-M-yyyy hh:mm a");
            String strDate = f.format(r.getFecha());
            
            datos.setValueAt(strDate, fila, 0);
            datos.setValueAt(r.getPropietario().getNombreCompleto(), fila, 1);
            datos.setValueAt(r.getMonto(), fila, 2);
            fila++;
        }
       
        tPendientes.setModel(datos);    
    }

    @Override
    public void error(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
}
