/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaEscritorio;

import controlador.ControladorControlPropietario;
import controlador.VistaControlPropietario;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.BonificacionAsignada;
import logica.Notificacion;
import logica.Propietario;
import logica.Recarga;
import logica.Transito;
import logica.Vehiculo;

/**
 *

 */
public class ControlPropietarioDialogo extends javax.swing.JDialog implements VistaControlPropietario{

    /**
     * Creates new form ControlPropietarioDialogo
     */
    private ControladorControlPropietario controlador;
    
    public ControlPropietarioDialogo(java.awt.Frame parent, boolean modal, Propietario propietario) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        controlador = new ControladorControlPropietario(propietario, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRecargar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tBonificaciones = new javax.swing.JTable();
        lCantidadNotificaciones = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tNotificaciones = new javax.swing.JTable();
        lSaldo = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tTransitos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        lCantidadVehiculos = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tVehiculos = new javax.swing.JTable();
        lCantidadBonificaciones = new javax.swing.JLabel();
        lCantidadTransitos = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tRecargas = new javax.swing.JTable();
        lCantidadRecargas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnRecargar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        tBonificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre bonificación", "Puesto", "FechaAsignada"
            }
        ));
        jScrollPane6.setViewportView(tBonificaciones);

        lCantidadNotificaciones.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lCantidadNotificaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCantidadNotificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notificacion.png"))); // NOI18N
        lCantidadNotificaciones.setText("2");
        lCantidadNotificaciones.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        tNotificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Fecha ", "Mensaje"
            }
        ));
        jScrollPane7.setViewportView(tNotificaciones);

        lSaldo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lSaldo.setForeground(new java.awt.Color(51, 153, 0));
        lSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinero.png"))); // NOI18N
        lSaldo.setText("000");
        lSaldo.setToolTipText("");
        lSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lNombre.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        lNombre.setText("Propietario BLA BLA");
        lNombre.setToolTipText("");
        lNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tTransitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Puesto", "Matricula", "Tarifa", "Tarifa(Monto)", "Binific.", "Bonific.(monto)", "Monto pagado", "Fecha"
            }
        ));
        jScrollPane8.setViewportView(tTransitos);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lCantidadVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lCantidadVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCantidadVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coche.png"))); // NOI18N
        lCantidadVehiculos.setText("2");
        lCantidadVehiculos.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Modelo", "Color", "#Transitos", "Monto total"
            }
        ));
        jScrollPane10.setViewportView(tVehiculos);

        lCantidadBonificaciones.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lCantidadBonificaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCantidadBonificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bonificaciones.png"))); // NOI18N
        lCantidadBonificaciones.setText("2");
        lCantidadBonificaciones.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lCantidadTransitos.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lCantidadTransitos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCantidadTransitos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transito.png"))); // NOI18N
        lCantidadTransitos.setText("2");
        lCantidadTransitos.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tRecargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha recarga", "Monto", "Estado", "Administrador"
            }
        ));
        jScrollPane9.setViewportView(tRecargas);

        lCantidadRecargas.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lCantidadRecargas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCantidadRecargas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recarga.png"))); // NOI18N
        lCantidadRecargas.setText("2");
        lCantidadRecargas.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRecargar, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lCantidadNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lCantidadTransitos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lCantidadVehiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(lCantidadBonificaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lCantidadRecargas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane9))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(455, 455, 455))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lCantidadVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lCantidadBonificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(lCantidadTransitos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(lCantidadRecargas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRecargar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lCantidadNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        // TODO add your handling code here:
        new RecargaSaldoDialogo(this, false, controlador.getPropietario()).setVisible(true);
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        controlador.borrar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        controlador.salir();
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lCantidadBonificaciones;
    private javax.swing.JLabel lCantidadNotificaciones;
    private javax.swing.JLabel lCantidadRecargas;
    private javax.swing.JLabel lCantidadTransitos;
    private javax.swing.JLabel lCantidadVehiculos;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lSaldo;
    private javax.swing.JTable tBonificaciones;
    private javax.swing.JTable tNotificaciones;
    private javax.swing.JTable tRecargas;
    private javax.swing.JTable tTransitos;
    private javax.swing.JTable tVehiculos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void error(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    @Override
    public void cargarNombre(String nombreCompleto) {
        lNombre.setText(nombreCompleto);
    }

    @Override
    public void cargarSaldo(float saldo) {
        lSaldo.setText("$ "+String.valueOf(saldo));
    }

    @Override
    public void mostrarVehiculos(ArrayList<Vehiculo> vehiculos) {
        lCantidadVehiculos.setText(String.valueOf(vehiculos.size()));
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Matrícula");
        datos.addColumn("Modelo");
        datos.addColumn("Color");
        datos.addColumn("#Transitos");
        datos.addColumn("Monto total");

        datos.setRowCount(vehiculos.size());
        int fila = 0;
        for(Vehiculo v:vehiculos){
            datos.setValueAt(v.getMatricula(), fila, 0);
            datos.setValueAt(v.getModelo(), fila, 1);
            datos.setValueAt(v.getColor(), fila, 2);
            datos.setValueAt(v.getTransitos().size(), fila, 3);
            //HAY QUE HACER EL MÉTODO PARA EL CONTROL DE GASTO DEL VEHÍCULO. También hay que arreglar el costo del tránsito
            datos.setValueAt(v.calcularGasto(), fila, 4);

            fila++;
        }
       
        tVehiculos.setModel(datos);
    }

    @Override
    public void mostrarBonificaciones(ArrayList<BonificacionAsignada> bonificaciones) {
        lCantidadBonificaciones.setText(String.valueOf(bonificaciones.size()));
        
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Nombre bonificación");
        datos.addColumn("Puesto");
        datos.addColumn("Fecha asignada");

        datos.setRowCount(bonificaciones.size());
        int fila = 0;
        for(BonificacionAsignada b:bonificaciones){
            datos.setValueAt(b.getTipo().getNombre(), fila, 0);
            datos.setValueAt(b.getPuesto().getNombre(), fila, 1);
            
            //FORMATEAR LA FECHA
            Format f = new SimpleDateFormat("dd-M-yyyy");
            String strDate = f.format(b.getFechaAsignada());
            datos.setValueAt(strDate, fila, 2);
            fila++;
        }
       
        tBonificaciones.setModel(datos);
    }

    @Override
    public void mostrarTransitos(ArrayList<Transito> transitos) {
        lCantidadTransitos.setText(String.valueOf(transitos.size()));
       
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Puesto");
        datos.addColumn("Matrícula");
        datos.addColumn("Tarifa");
        datos.addColumn("Tarifa (monto)");
        datos.addColumn("Bonific.");
        datos.addColumn("Bonific. (monto)");
        datos.addColumn("Monto pagado");
        datos.addColumn("Fecha");

        datos.setRowCount(transitos.size());
        int fila = 0;
        for(Transito t:transitos){
            datos.setValueAt(t.getPuesto().getNombre(), fila, 0);
            datos.setValueAt(t.getVehiculo().getMatricula(), fila, 1);
            datos.setValueAt(t.getVehiculo().getCategoria().getNombre(), fila, 2);
            
            datos.setValueAt(t.getTarifa(), fila, 3);
            if (t.getBonificacion()!=null){
                datos.setValueAt(t.getBonificacion().getTipo().getNombre(), fila, 4);
            }else{
                datos.setValueAt("", fila, 4);
            }
            
            datos.setValueAt(t.getBonificacionAplicada(), fila, 5);
            datos.setValueAt(t.getImporte(), fila, 6);
            
            //FORMATEAR LA FECHA
            Format f = new SimpleDateFormat("dd-M-yyyy hh:mm a");
            String strDate = f.format(t.getFecha());
            
            datos.setValueAt(strDate, fila, 7);
            
            fila++;
        }
       
        tTransitos.setModel(datos);
    }

    @Override
    public void mostrarRecargas(ArrayList<Recarga> recargasProp) {
        lCantidadRecargas.setText(String.valueOf(recargasProp.size()));
        
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Fecha recarga");
        datos.addColumn("Monto");
        datos.addColumn("Estado");
        datos.addColumn("Administrador");
        
        datos.setRowCount(recargasProp.size());
        int fila = 0;
        for(Recarga r:recargasProp){
            Format f = new SimpleDateFormat("dd-M-yyyy hh:mm a");
            String strDate = f.format(r.getFecha());
            datos.setValueAt(strDate, fila, 0);
            datos.setValueAt(r.getMonto(), fila, 1);
            datos.setValueAt(r.getEstado(), fila, 2);
            datos.setValueAt(r.getAdministrador(), fila, 3);
            
            fila++;
        }
       
        tRecargas.setModel(datos);
    }

    @Override
    public void mostrarNotificaciones(ArrayList<Notificacion> notificaciones) {
        lCantidadNotificaciones.setText(String.valueOf(notificaciones.size()));
        
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Fecha");
        datos.addColumn("Mensaje");

        datos.setRowCount(notificaciones.size());
        int fila = 0;
        for(Notificacion n: notificaciones){
            Format f = new SimpleDateFormat("dd-M-yyyy");
            String strDate = f.format(n.getFecha());
            
            datos.setValueAt(strDate, fila, 0);
            datos.setValueAt(n.getMensaje(), fila, 1);

            fila++;
        }
       
        tNotificaciones.setModel(datos);
    }

}
