/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaEscritorio;

import controlador.ControladorEmularTransito;
import controlador.VistaEmularTransito;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import logica.PeajeException;
import logica.Puesto;
import logica.Tarifa;
import logica.Transito;

/**
 *

 */
public class EmularTransitoDialogo extends javax.swing.JDialog implements VistaEmularTransito {

    private ControladorEmularTransito controlador;

    /**
     * Creates new form EmularTransito
     */
    public EmularTransitoDialogo(java.awt.Frame parent, boolean modal) { //
        super(parent, modal);
        initComponents();
        controlador = new ControladorEmularTransito(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTarifas = new javax.swing.JTable();
        comboPuestos = new javax.swing.JComboBox();
        tfMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bCerrar = new javax.swing.JButton();
        bRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Emular  transito");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Puestos:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tarifas:");

        tTarifas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Categoria", "Monto"
            }
        ));
        jScrollPane1.setViewportView(tTarifas);
        if (tTarifas.getColumnModel().getColumnCount() > 0) {
            tTarifas.getColumnModel().getColumn(0).setPreferredWidth(125);
        }

        comboPuestos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPuestosItemStateChanged(evt);
            }
        });
        comboPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPuestosActionPerformed(evt);
            }
        });

        tfMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMatriculaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ingrese matricula:");

        bCerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bCerrar.setText("Cerrar");
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });

        bRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bRegistrar.setText("Registrar");
        bRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRegistrarMouseClicked(evt);
            }
        });
        bRegistrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bRegistrarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bRegistrar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(comboPuestos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bCerrar)
                        .addGap(181, 181, 181))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRegistrar)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(bCerrar)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatriculaActionPerformed
        // TODO add your handling code here:
        registrarTransito();
    }//GEN-LAST:event_tfMatriculaActionPerformed

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_bCerrarActionPerformed

    private void comboPuestosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPuestosItemStateChanged
        // TODO add your handling code here:     

    }//GEN-LAST:event_comboPuestosItemStateChanged

    private void bRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRegistrarMouseClicked
        // TODO add your handling code here:
        registrarTransito();

    }//GEN-LAST:event_bRegistrarMouseClicked

    private void bRegistrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bRegistrarKeyPressed
        // TODO add your handling code here:
        registrarTransito();
    }//GEN-LAST:event_bRegistrarKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void comboPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPuestosActionPerformed
        // TODO add your handling code here:
        if (comboPuestos.getSelectedIndex() > 0) {
            comboPuestos();
        } else {
            mostrarTarifasVacio();
        }

    }//GEN-LAST:event_comboPuestosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bRegistrar;
    private javax.swing.JComboBox comboPuestos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tTarifas;
    private javax.swing.JTextField tfMatricula;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarPuestos(ArrayList<Puesto> puestos) {
        comboPuestos.addItem("Seleccione un puesto");
        for (Puesto p : puestos) {
            comboPuestos.addItem(p);
        }
    }

    public void comboPuestos() {
        controlador.hayPuestoSeleccionado((Puesto) comboPuestos.getSelectedItem());
    }

    @Override
    public void mostrarTarifas(ArrayList<Tarifa> tarifas) {

        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Categoria");
        datos.addColumn("Monto");

        datos.setRowCount(tarifas.size());
        int fila = 0;
        for (Tarifa t : tarifas) {
            datos.setValueAt(t.getCategoria().getNombre(), fila, 0);
            datos.setValueAt(t.getMonto(), fila, 1);

            fila++;
        }
        tTarifas.setModel(datos);
    }

    @Override
    public void mostrarTarifasVacio() {
        DefaultTableModel datos = (DefaultTableModel) tTarifas.getModel();
        datos.setRowCount(0);
        tTarifas.setModel(datos);
    }

    public void registrarTransito() {
        String matricula = tfMatricula.getText();
        try {
            if (comboPuestos.getSelectedIndex() == 0) {
                controlador.noHayPuestoSeleccionado();
            }
            controlador.agregarTransito(matricula);
        } catch (PeajeException ex) {
            error(ex.getMessage());
        }

    }

    @Override
    public void limpiarCampos() {
        tfMatricula.setText("");
    }

    @Override
    public void mostrarResultadoBonificacion(Transito nuevo) {

        String m1 = "Nuevo Tránsito realizado por " + nuevo.getVehiculo().getPropietario().getNombreCompleto() + "\n"
                + "Categoría: " + nuevo.getVehiculo().getCategoria().getNombre() + "\n"
                + "Se aplica bonificación " + nuevo.getBonificacion().getTipo().getNombre() + "\n"
                + "Costo: $ " + nuevo.getImporte() + "\n"
                + "Saldo restante: $" + nuevo.getVehiculo().getPropietario().getSaldo();
        JOptionPane.showMessageDialog(this, m1);

    }

    @Override
    public void mostrarResultadoSinBonificacion(Transito nuevo) {
        String m2 = "Nuevo Tránsito realizado por " + nuevo.getVehiculo().getPropietario().getNombreCompleto() + "\n"
                + "Categoría: " + nuevo.getVehiculo().getCategoria().getNombre() + "\n"
                + "Costo: $ " + nuevo.getImporte() + "\n"
                + "Saldo restante: $" + nuevo.getVehiculo().getPropietario().getSaldo();
        JOptionPane.showMessageDialog(this, m2);

    }

    @Override
    public void error(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

}
