/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaEscritorio;

import vistaEscritorio.AprobacionRecargasDialogo;
import logica.Administrador;
import logica.Fachada;
import vistaEscritorio.AsignarBonificacionesDialogo;
import vistaEscritorio.EmularTransitoDialogo;

/**
 *

 */
public class MenuAdministrador extends javax.swing.JFrame {

    private Administrador admin;

    /**
     * Creates new form Menu
     */

    public MenuAdministrador(Administrador admin) {
        this.admin = admin;
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemNuevoTransito = new javax.swing.JMenuItem();
        itemAprobacionRecargas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemAsignarBonificaciones = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MENU ADMINISTRADOR");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenu1.setText("Emular");

        itemNuevoTransito.setText("Tránsito");
        itemNuevoTransito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNuevoTransitoActionPerformed(evt);
            }
        });
        jMenu1.add(itemNuevoTransito);

        itemAprobacionRecargas.setText("Aprobación recargas");
        itemAprobacionRecargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAprobacionRecargasActionPerformed(evt);
            }
        });
        jMenu1.add(itemAprobacionRecargas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Asignar");

        itemAsignarBonificaciones.setText("Bonificaciones");
        itemAsignarBonificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAsignarBonificacionesActionPerformed(evt);
            }
        });
        jMenu2.add(itemAsignarBonificaciones);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemNuevoTransitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoTransitoActionPerformed
        // TODO add your handling code here:
        new EmularTransitoDialogo(this,false).setVisible(true);
    }//GEN-LAST:event_itemNuevoTransitoActionPerformed

    private void itemAsignarBonificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAsignarBonificacionesActionPerformed
        // TODO add your handling code here:
        new AsignarBonificacionesDialogo(this,false,admin).setVisible(true);
    }//GEN-LAST:event_itemAsignarBonificacionesActionPerformed


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Fachada.getInstancia().logOutAdministrador(admin);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void itemAprobacionRecargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAprobacionRecargasActionPerformed
           new AprobacionRecargasDialogo(this,false,admin).setVisible(true);
    }//GEN-LAST:event_itemAprobacionRecargasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAprobacionRecargas;
    private javax.swing.JMenuItem itemAsignarBonificaciones;
    private javax.swing.JMenuItem itemNuevoTransito;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
